# Generated by Django 3.0.1 on 2021-02-06 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('value', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='余额')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
            },
        ),
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('cat', models.IntegerField(choices=[(1, '收入'), (2, '支出')], verbose_name='收支')),
            ],
            options={
                'verbose_name': '账户收支类别',
                'verbose_name_plural': '账户收支类别',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '银行',
                'verbose_name_plural': '银行',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('cat', models.IntegerField(choices=[(1, '流动资产'), (2, '流动负债'), (3, '固定资产'), (4, '长期负债'), (5, '投资')], verbose_name='类别')),
                ('driver', models.CharField(blank=True, max_length=40, null=True, verbose_name='数据驱动')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='货币名称')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='汇率')),
            ],
            options={
                'verbose_name': '币种',
                'verbose_name_plural': '币种',
            },
        ),
        migrations.CreateModel(
            name='InvProj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='代码')),
                ('url', models.URLField(blank=True, null=True, verbose_name='链接')),
                ('isopen', models.BooleanField(verbose_name='是否存续')),
                ('start', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('quote_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='查询代号')),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='现价')),
                ('buy_amount', models.DecimalField(decimal_places=4, max_digits=16, null=True)),
                ('sell_amount', models.DecimalField(decimal_places=4, max_digits=16, null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16, null=True)),
                ('buy_value', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('sell_value', models.DecimalField(decimal_places=2, max_digits=16, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='现存价值')),
                ('dividends', models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='分红')),
                ('irr', models.DecimalField(decimal_places=4, max_digits=16, null=True, verbose_name='年化率')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='注释')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.Bank', verbose_name='银行')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Category', verbose_name='类别')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Currency', verbose_name='币种')),
            ],
            options={
                'verbose_name': '投资项目',
                'verbose_name_plural': '投资项目',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '风险级别',
                'verbose_name_plural': '风险级别',
            },
        ),
        migrations.CreateModel(
            name='InvRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('cat', models.IntegerField(choices=[(1, '买'), (2, '卖'), (3, '分红')], verbose_name='类别')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='数额')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=16, verbose_name='价格')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, verbose_name='总价')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=16, verbose_name='佣金')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='汇率')),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.InvProj', verbose_name='投资项目')),
            ],
            options={
                'verbose_name': '投资记录',
                'verbose_name_plural': '投资记录',
            },
        ),
        migrations.AddField(
            model_name='invproj',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Risk', verbose_name='风险级别'),
        ),
        migrations.CreateModel(
            name='AccountRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('value', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='金额')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='注释')),
                ('acct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.Account', verbose_name='账户')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.AccountCategory', verbose_name='账户收支类别')),
            ],
            options={
                'verbose_name': '账户收支',
                'verbose_name_plural': '账户收支',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Bank', verbose_name='银行'),
        ),
        migrations.AddField(
            model_name='account',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Category', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Currency', verbose_name='币种'),
        ),
    ]
